# Testing pipeline

name: Testing

on:
  push:
    branches: [ main, readability-fixes ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
        run: pylint --rcfile pylintrc sensor/*.py